# Input Values

In [24]:
import ee
import numpy as np
from openet.refetgee import calcs
ee.Initialize()

## Input Latitude, Longitude

In [25]:
area = ee.Geometry.Point( -118.77388, 39.4575)
# area = ee.Geometry.Point( -107.2080, 39.3623)

## Input Dates

In [26]:
img = ee.Image(ee.ImageCollection('IDAHO_EPSCOR/GRIDMET').filterDate('2015-01-01', '2019-01-04').first())
# img = ee.Image(ee.ImageCollection('IDAHO_EPSCOR/GRIDMET').filterDate('2018-01-01', '2019-01-04').first())

## tmin   ee.Image

In [27]:
tmin = img.select(['tmmn']).subtract(273.15).rename(['tmin'])

## tmax   ee.Image

In [28]:
tmax = img.select(['tmmx']).subtract(273.15).rename(['tmax'])

## elev   ee.Image, ee.Number

In [29]:
elev = ee.Image('projects/earthengine-legacy/assets/projects/climate-engine/gridmet/elevation').rename(['elev'])

## ea   ee.Image

In [30]:
ea = calcs._actual_vapor_pressure(
                q=img.select(['sph']),
                pair=calcs._air_pressure(elev, 'asce')).rename(['ea'])

## rs   ee.Image

In [31]:
rs = img.select(['srad']).multiply(0.0864).rename(['rs'])

## uz   ee.Image

In [32]:
uz = img.select(['vs']).rename(['uz'])

## zw   ee.Number

In [33]:
zw = ee.Number(10)

## lat   ee.Image, ee.Number

In [34]:
lat = ee.Image('projects/earthengine-legacy/assets/projects/climate-engine/gridmet/elevation')\
                .multiply(0).add(ee.Image.pixelLonLat().select('latitude'))\
                .rename(['lat'])

## long   ee.Image, ee.Number

In [35]:
long = ee.Image('projects/earthengine-legacy/assets/projects/climate-engine/gridmet/elevation')\
                .multiply(0).add(ee.Image.pixelLonLat().select('longitude'))\
                .rename(['long'])

## Reduce/Get Variable Values

In [36]:
data = ee.Image.pixelLonLat().addBands([tmin, tmax, elev, ea, rs, uz, lat, long])

In [37]:
data = data.reduceRegion(
  reducer=ee.Reducer.toList(),
  geometry=area,
  scale=1000);

## tmin   ee.Image

In [38]:
tmin_ = np.array((ee.Array(data.get("tmin")).getInfo()))
tmin_

array([-17.66766968])

## tmax   ee.Image

In [39]:
tmax_ = np.array((ee.Array(data.get("tmax")).getInfo()))
tmax_

array([-0.09540405])

## elev   ee.Image, ee.Number

In [40]:
elev_ = np.array((ee.Array(data.get("elev")).getInfo()))
elev_

array([1206.64001465])

## ea   ee.Image

In [41]:
ea_ = np.array((ee.Array(data.get("ea")).getInfo()))
ea_

array([0.25796463])

## rs   ee.Image

In [42]:
rs_ = np.array((ee.Array(data.get("rs")).getInfo()))
rs_

array([8.35973196])

## uz   ee.Image

In [43]:
uz_ = np.array((ee.Array(data.get("uz")).getInfo()))
uz_

array([1.11040497])

## zw   ee.Number

In [44]:
ee.Number(10).getInfo()

10

## lat   ee.Image, ee.Number

In [45]:
lat_ = np.array((ee.Array(data.get("lat")).getInfo()))
lat_

array([39.45849885])

## long   ee.Image, ee.Number

In [46]:
long_ = np.array((ee.Array(data.get("long")).getInfo()))
long_

array([-118.77075529])

# Output Values

## ETR Carbondale
Latitude: 39.3623
Longitude: -107.2080
Western Slope

In [47]:
from datetime import datetime
start = ee.Date('2018-01-01')
finish = ee.Date('2018-01-04')

img = ee.ImageCollection('IDAHO_EPSCOR/GRIDMET').filterDate(start, finish).first() 

In [48]:
img.date().get('day').getInfo()

1

In [49]:
img.date().get('month').getInfo()

1

In [50]:
img.date().get('year').getInfo()

2018

In [51]:
import ee
import openet.refetgee

etr = openet.refetgee.Daily.gridmet(img).etr\
    .reduceRegion(reducer=ee.Reducer.first(),
                  geometry=ee.Geometry.Point( -107.2080, 39.3623),
                  scale=1000)\
    .getInfo()

float(etr['etr'])

tmax: ee.Image({
  "functionInvocationValue": {
    "functionName": "Image.subtract",
    "arguments": {
      "image1": {
        "functionInvocationValue": {
          "functionName": "Image.select",
          "arguments": {
            "bandSelectors": {
              "constantValue": [
                "tmmx"
              ]
            },
            "input": {
              "functionInvocationValue": {
                "functionName": "Collection.first",
                "arguments": {
                  "collection": {
                    "functionInvocationValue": {
                      "functionName": "Collection.filter",
                      "arguments": {
                        "collection": {
                          "functionInvocationValue": {
                            "functionName": "ImageCollection.load",
                            "arguments": {
                              "id": {
                                "constantValue": "IDAHO_EPSCOR/GRIDMET"
           

1.7293712055273676

## ETR Fallon NV
Latitude: 39.4575
Longitude:  -118.77388
Date: 2015-07-01

In [52]:
from datetime import datetime
start = ee.Date('2015-07-01')
finish = ee.Date('2015-07-02')

img = ee.ImageCollection('IDAHO_EPSCOR/GRIDMET').filterDate(start, finish).first() 

In [53]:
img.date().get('day').getInfo()

1

In [54]:
img.date().get('month').getInfo()

7

In [55]:
img.date().get('year').getInfo()

2015

In [56]:
import ee
import openet.refetgee

etr = openet.refetgee.Daily.gridmet(img).etr\
    .reduceRegion(reducer=ee.Reducer.first(),
                  geometry=ee.Geometry.Point(  -118.77388, 39.4575),
                  scale=1000)\
    .getInfo()

# print('ETr: {:.2f} mm'.format(float(etr['etr'])))
float(etr['etr'])

tmax: ee.Image({
  "functionInvocationValue": {
    "functionName": "Image.subtract",
    "arguments": {
      "image1": {
        "functionInvocationValue": {
          "functionName": "Image.select",
          "arguments": {
            "bandSelectors": {
              "constantValue": [
                "tmmx"
              ]
            },
            "input": {
              "functionInvocationValue": {
                "functionName": "Collection.first",
                "arguments": {
                  "collection": {
                    "functionInvocationValue": {
                      "functionName": "Collection.filter",
                      "arguments": {
                        "collection": {
                          "functionInvocationValue": {
                            "functionName": "ImageCollection.load",
                            "arguments": {
                              "id": {
                                "constantValue": "IDAHO_EPSCOR/GRIDMET"
           

8.914614227473201